"""Hardcoded Jira execution values for the MVP integration boundary."""

LABEL_AI_READY = "ai-ready"
LABEL_AI_CLAIMED = "ai-claimed"
LABEL_AI_FAILED = "ai-failed"
LABEL_AI_EXECUTION_APPROVED = "ai-execution-approved"
LABEL_DO_NOT_AUTOMATE = "do-not-automate"

STATUS_TODO = "To Do"
STATUS_IN_PROGRESS = "In Progress"
STATUS_IN_REVIEW = "In Review"

FIELD_AGENT_ASSIGNED_COMPONENT = "agent_assigned_component"
FIELD_AGENT_RETRY_COUNT = "agent_retry_count"
FIELD_AGENT_CAPABILITIES_NEEDED = "agent_capabilities_needed"
FIELD_REPOSITORY = "repository"
FIELD_REPO_PATH = "repo_path"
FIELD_MAX_ATTEMPTS = "max_attempts"

EVENT_JIRA_COMPENSATION_STARTED = "jira_compensation_started"
EVENT_JIRA_COMPENSATION_COMPLETED = "jira_compensation_completed"
EVENT_JIRA_COMPENSATION_FAILED = "jira_compensation_failed"

EVENT_JIRA_EXECUTION_STARTED = "jira_execution_started"
EVENT_JIRA_EXECUTION_COMPLETED = "jira_execution_completed"
EVENT_JIRA_EXECUTION_FAILED = "jira_execution_failed"
EVENT_JIRA_EXECUTION_IN_REVIEW = "jira_execution_in_review"
EVENT_JIRA_EXECUTION_RELEASED_WITHOUT_PR = "jira_execution_released_without_pr"
EVENT_JIRA_EXECUTION_FAILURE_REPORT_FAILED = "jira_execution_failure_report_failed"

__all__ = [
    "EVENT_JIRA_COMPENSATION_COMPLETED",
    "EVENT_JIRA_COMPENSATION_FAILED",
    "EVENT_JIRA_COMPENSATION_STARTED",
    "EVENT_JIRA_EXECUTION_COMPLETED",
    "EVENT_JIRA_EXECUTION_FAILED",
    "EVENT_JIRA_EXECUTION_FAILURE_REPORT_FAILED",
    "EVENT_JIRA_EXECUTION_IN_REVIEW",
    "EVENT_JIRA_EXECUTION_RELEASED_WITHOUT_PR",
    "EVENT_JIRA_EXECUTION_STARTED",
    "FIELD_AGENT_ASSIGNED_COMPONENT",
    "FIELD_AGENT_CAPABILITIES_NEEDED",
    "FIELD_AGENT_RETRY_COUNT",
    "FIELD_MAX_ATTEMPTS",
    "FIELD_REPOSITORY",
    "FIELD_REPO_PATH",
    "LABEL_AI_CLAIMED",
    "LABEL_AI_EXECUTION_APPROVED",
    "LABEL_AI_FAILED",
    "LABEL_AI_READY",
    "LABEL_DO_NOT_AUTOMATE",
    "STATUS_IN_PROGRESS",
    "STATUS_IN_REVIEW",
    "STATUS_TODO",
]
